---
# Creating Local Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xyz-volume
  labels:
    type: local
spec:
  #we use local node storage here!
  #kubectl get storageclass
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/index.html"

---
# Creating Local Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xyz-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi