# Added a taint on kube-woker-2 such that:
# kubectl taint nodes kube-woker-2 color=green:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
  tolerations:
  - key: "nvidia-gpu"
    operator: "Equal"
    value: "absent"
    effect: "NoSchedule"